name: Build Home-Portal App

trigger:
  branches:
    include:
    - 'master' 

stages:
- stage: Build
  jobs:
  - job: Build_Client
    pool:
      vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
  displayName: 'Install Node.js'
  - script: |
    cd client
    npm install
    npm run build
  displayName: 'npm install and run build'
