name: Build Home-Portal App

trigger:
  branches:
    include:
    - 'master'

stages:
- stage: Build
  jobs:
  - job: Build_Client
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '10.x'
  - script:
    cd client